### ISSUE TITLE
⭐: New Habit

### ISSUE THREAD

**Issue by paulywill** [chingu-voyages/v8-geckos-team-07#11]
**Task List/ WIPs**

- [x] Habit Form (included various details about the habit to track) #42 
- [x] CSS modal function #60 
- [x] Database Schema #54 
- [x] Navigation smooth #51 
- [x] Move NewHabit.js/.css functionality to parent level (Dashboard.js)
----
- [ ] OPTIONAL: Share with social media
- [ ] OPTIONAL: Carrot / stick after deadline
- [ ] *BONUS: look-up and cite real research on ideals timeline
----

**User Story**
- Bob want to exercise more.
- He navigates to "Habit Tracker" online web app that will motivate Bob to establish this new habit.
- There is a Google sign-in button (we live in a very limited world) and Bob is signs up using his Google credentials.
- Bob fills out an initial form for the new habit he want to track, which will include the description, frequency of his check-ins, and duration of time during which he will track.
- As a bonus Bob is able to easily share his progress on FB, Twitter, or via email link to his page.
- As another bonus Bob is given further reading material and/or research references to look at during his journey

**Acceptance Criteria**
- [x] - New habit form is validated that appropriate data was entered
- [x] - Google / firebase credentials are tested and working as intended
- [x] - database updates correctly: new user added with correct validated habit details
- [ ] - Social buttons are linking are working correctly
- [ ] - Smooth navigation from initial login screen to user signing up (header is updated correctly; user state functioning)

**Definition of Done**
😀 Team is happy!

**Comment by pjconnolly12** [comment]
@paulywill I just want to confirm because I haven't dealt with github issues before, is this just to track that this is something we need to do? Should Sara or I be getting this form created before our meeting? just checking to make sure I fully understand

**Comment by paulywill** [comment]
Just planning for Sprint 3.

@pjconnolly12 yes sorry, my intention is always to explain or cover things I've done planning wise on github at our meetings. I was thinking, and it's really up to you and @SaraSweetie, but I think both of you should work together on the forms for Sprint 3. 

So we'll talk about it more at our meeting, but basically, since Sara is leading the charge on the design and look of the front-end and you've ideally set up the schema of the backend I think the two of you should team up on this feature.

**Comment by paulywill** [comment]
Re-opened because this feature is not fully implemented, just a few of the work items.
