### ISSUE TITLE
🦎 Bell, Whistles, and Best Practices

### ISSUE THREAD

**Issue by paulywill** [chingu-voyages/v8-geckos-team-07#115]
- [ ] Iceboxed/Wishlist features #89 
- [ ] Best practices for React
- [ ] Measure performance
- [ ] Measure users 
- [ ] Cite academic "habit acquistion" research
