### ISSUE TITLE
Chrome Browser Extension: Making the habit check in easier.

### ISSUE THREAD

**Issue by paulywill** [chingu-voyages/v8-geckos-team-07#129]
## Task List/ WIPs
- [ ] - prototype for Chrome extension that ties into webapp

## User Story
Stacey opens her Chrome browser and reminded gently to check-in her habit. She can either log in the data quickly or snooze/remind herself later; or tapout for today

## Acceptance Criteria
- [ ] - Extension connects to user OAuth credentials/dbase
- [ ] - Extension updates dbase correctly
- [ ] - Extension remembers to remind based on last timestamp of entry
- [ ] - Extension maintains session or state (experimenting and testing required)

## Definition of Done**
😀 User participation is easier and seamless with Chrome Extension.
