### ISSUE TITLE
⭐: Daily Check-In Form

### ISSUE THREAD

**Issue by paulywill** [chingu-voyages/v8-geckos-team-07#13]
## Task List/ WIPs
- [x] - updates backend #67 
- [x] - button should be available to show (header / dashboard) #68 
- [x] - message to indicated database was updated successfully #69

## User Story

Bob is able to log in and do his daily or weekly check-in on his habit.
His data is updated into some database and is reflected on the stats page (via overall counter or graphs).

## Acceptance Criteria
- [x] - the user has to login
- [x] - check-in form validates
- [x] - API connects and updates database #67 
- [x] - message displays success
- [ ] - the stats page is able to retrieve new data and update graphs and numerical data 

## Definition of Done**
Check-in form is completely working and updating correctly after user logs in. 
Only Bob can check-in.
Another user should not be able to check-in as Bob.

😀 Team is happy!

**Comment by paulywill** [comment]
We just have to reflect changes in the widgets/stats page and this feature is completed.
