### ISSUE TITLE
⭐: Progress/Stats Page

### ISSUE THREAD

**Issue by paulywill** [chingu-voyages/v8-geckos-team-07#14]
- [x] Empty Component to place widgets -> @SaraSweetie #55

- [x] Heatmap / Doughnut / Circle Stats Widget -> #56

- [x] Countdown Clock  Stats Widget -> #57

~~ - [ ] Weekly/Monthly swipe/zoom out Progress Widget ~~

~~ - [ ] Toggle Daily/Weekly/Monthly ~~

~~ - [ ] Stats share option (FB/Twitter/Instagram) Widget -> #58 ~~

**Comment by paulywill** [comment]
Breaking down this feature into separate task items.
