### ISSUE TITLE
🚨: MVP 

### ISSUE THREAD

**Issue by paulywill** [chingu-voyages/v8-geckos-team-07#35]
**User Story**

- [x] - Seamless login flow #51 
- [x] - Setup new habit  #11 
- [x] - Check-in Functionality #13 
- [x] - Stats/progress page #14  
- [x] - User Profile/Settings Page | Header/Dashboard

**Acceptance Criteria**

- The basic version of the user story from beginning to end.

**Definition of Done**
- Every member of the team is satisfied with hosted `development` branch we push to `master`.
