### ISSUE TITLE
⭐: User Profile / Settings page | Header/Dashboard

### ISSUE THREAD

**Issue by paulywill** [chingu-voyages/v8-geckos-team-07#52]
**Task List**
- [x] Header mockup -> #63
- [x] Red button that unlinks social connection AND deletes data from MongoDB -> #61 
~~-Toggle for daily/weekly view -> #64~~
- [x] Place/user hamburger button for user profile/settings -> #62
- [x] Button/link in the hamburger menu for user settings -> #90 

**User Story**
The user is easily able to locate a settings page (right-clicking / drop-down) on the header.

Here the user can tweak things relating to their account, including unlinking and deleting their data by selection a "Remove Account" selection. This should be intuitive such as a big red button with verification.

**Acceptance Criteria**
- Settings page loads correctly and navigates accordingly
- Settings page will only show if user is logged in
- "Remove Account" feature should work seamlessly
- IDEALLY: unit tests to test this out

**Definition of Done**
- Team is happy
